### PR TITLE
dominant-color-picker: Adds svg support

### PR DESCRIPTION
**Pull request by ericmikkelsen**
This now reads in all the hex values from an SVG and sets the first one as the dominant color.

### CODE REVIEW

**Comment by lgladdy** [comment]
All seems sane to me! Thanks for the PR!

Only possible question, should we check if the user has GD installed for the use of the GD functions, or do you think it's safe to assume they have GD? Color Thief requires either GD or Imagick or Gmagick - but I'm not sure how many installs are likely to only have Imagick or Gmagick.

Maybe just add a graceful exit from get_top_left_pixel() if GD isn't available?

Also, feel free to update README.md and readme.txt with contribution credits for you or sproutsocial, whichever you like - you deserve credit :)

**Comment by ericmikkelsen** [comment]
Thanks @lgladdy!
I'll add the graceful exit, I know at the moment that Wordpress relies heavily on GD so it should always be there, but there's no reason I can't check.

**Comment by lgladdy** [comment]
@ericmikkelsen Perfect - thanks! You're probably right. I just get super cautious whenever I roll out a update to a plugin that's used by real people on production!

**Comment by ericmikkelsen** [comment]
Alright, you now have some graceful fallbacks if GD doesn't exist, and I dropped a line in there about us, but if you want me to update that changelog at all let me know.

Also it looks like the version in github is slightly behind the version on wordpress.org, Is that hiding somewhere else?

**Comment by lgladdy** [comment]
I'll check what's on wordpress.org and merge both this PR and that code - probably my fault at some point! Thanks for the update :)

**Comment by ericmikkelsen** [comment]
Anytime, thanks a million!

**Pull request merged**
